
import { describe, expect, it } from "vitest";

const accounts = simnet.getAccounts();
const address1 = accounts.get("wallet_1")!;

/*
  The test below is an example. To learn more, read the testing documentation here:
  https://docs.hiro.so/stacks/clarinet-js-sdk
*/

describe("example tests", () => {
  it("ensures simnet is well initalised", () => {
    expect(simnet.blockHeight).toBeDefined();
  });

  // it("shows an example", () => {
  //   const { result } = simnet.callReadOnlyFn("counter", "get-counter", [], address1);
  //   expect(result).toBeUint(0);
  // });
});
// test iteration case 4
// test iteration case 4
// test iteration case 12
// test iteration case 15
// test iteration case 17
// test iteration case 24
// test iteration case 25
// test iteration case 32
// test iteration case 37
// test iteration case 41
// test iteration case 42
// test iteration case 43
// test iteration case 48
// test iteration case 3
// test iteration case 8
// test iteration case 25
// test iteration case 27
// test iteration case 30
// test iteration case 33
// test iteration case 36
// test iteration case 40
// test iteration case 46
// test iteration case 49
// test iteration case 53
// test iteration case 55
// test iteration case 56
// test iteration case 57
// test iteration case 65
// test iteration case 66
// test iteration case 68
// test iteration case 78
// test iteration case 82
// test iteration case 84
// test iteration case 91
// test iteration case 107
// test iteration case 108
// test iteration case 110
// test iteration case 119
// test iteration case 120
// test iteration case 129
// test iteration case 132
// test iteration case 137
// test iteration case 139
// test iteration case 140
// test iteration case 145
// test iteration case 151
// test iteration case 152
// test iteration case 167
// test iteration case 177
// test iteration case 182
// test iteration case 188
// test iteration case 189
// test iteration case 190
// test iteration case 196
// test iteration case 204
// test iteration case 207
// test iteration case 212
// test iteration case 215
// test iteration case 217
// test iteration case 219
// test iteration case 221
// test iteration case 225
// test iteration case 226
// test iteration case 232
// test iteration case 235
// test iteration case 238
// test iteration case 242
// test iteration case 257
// test iteration case 260
// test iteration case 287
// test iteration case 291
// test iteration case 293
// test iteration case 7
// test iteration case 8
// test iteration case 12
// test iteration case 16
// test iteration case 29
// test iteration case 32
// test iteration case 37
// test iteration case 45
// test iteration case 46
// test iteration case 56
// test iteration case 58
// test iteration case 67
// test iteration case 68
// test iteration case 69
// test iteration case 72
// test iteration case 94
// test iteration case 105
// test iteration case 110
// test iteration case 114
// test iteration case 120
// test iteration case 124
// test iteration case 131
// test iteration case 141
// test iteration case 143
// test iteration case 145
// test iteration case 147
// test iteration case 162
// test iteration case 164
// test iteration case 165
// test iteration case 172
// test iteration case 175
// test iteration case 177
// test iteration case 181
// test iteration case 188
// test iteration case 192
// test iteration case 195
// test iteration case 205
// test iteration case 207
// test iteration case 216
// test iteration case 218
// test iteration case 2
// test iteration case 3
// test iteration case 5
// test iteration case 7
// test iteration case 13
// test iteration case 22
// test iteration case 23
// test iteration case 24
// test iteration case 27
// test iteration case 28
// test iteration case 35
// test iteration case 42
// test iteration case 63
// test iteration case 67
// test iteration case 79
// test iteration case 89
// test iteration case 102
// test iteration case 109
// test iteration case 114
// test iteration case 126
// test iteration case 135
// test iteration case 136
// test iteration case 148
// test iteration case 153
// test iteration case 156
// test iteration case 164
// test iteration case 175
// test iteration case 182
// test iteration case 188
// test iteration case 194
// test iteration case 197
// test iteration case 200
// test iteration case 219
// test iteration case 235
// test iteration case 245
// test iteration case 266
// test iteration case 273
// test iteration case 283
// test iteration case 286
// test iteration case 288
// test iteration case 289
// test iteration case 27
// test iteration case 33
// test iteration case 35
// test iteration case 39
// test iteration case 40
// test iteration case 48
// test iteration case 59
// test iteration case 63
// test iteration case 72
// test iteration case 74
// test iteration case 76
// test iteration case 83
// test iteration case 85
// test iteration case 90
// test iteration case 94
// test iteration case 99
// test iteration case 100
// test iteration case 101
// test iteration case 102
// test iteration case 103
// test iteration case 108
// test iteration case 113
// test iteration case 114
// test iteration case 116
// test iteration case 125
// test iteration case 129
// test iteration case 132
// test iteration case 148
// test iteration case 162
// test iteration case 164
// test iteration case 173
// test iteration case 174
// test iteration case 178
// test iteration case 180
// test iteration case 183
// test iteration case 192
// test iteration case 204
// test iteration case 212
// test iteration case 214
// test iteration case 222
// test iteration case 225
// test iteration case 234
// test iteration case 235
// test iteration case 248
// test iteration case 251
// test iteration case 258
// test iteration case 5
// test iteration case 11
// test iteration case 15
// test iteration case 17
// test iteration case 22
// test iteration case 33
// test iteration case 36
// test iteration case 39
// test iteration case 44
// test iteration case 49
// test iteration case 51
// test iteration case 54
// test iteration case 101
// test iteration case 104
// test iteration case 114
// test iteration case 120
// test iteration case 124
// test iteration case 126
// test iteration case 127
// test iteration case 142
// test iteration case 150
// test iteration case 162
// test iteration case 168
// test iteration case 170
// test iteration case 178
// test iteration case 182
// test iteration case 187
// test iteration case 210
// test iteration case 217
// test iteration case 221
// test iteration case 2
// test iteration case 9
// test iteration case 17
// test iteration case 38
// test iteration case 42
// test iteration case 48
// test iteration case 54
// test iteration case 62
// test iteration case 5
// test iteration case 10
// test iteration case 12
// test iteration case 15
// test iteration case 18
// test iteration case 36
// test iteration case 44
// test iteration case 65
// test iteration case 76
// test iteration case 85
// test iteration case 86
// test iteration case 89
// test iteration case 95
// test iteration case 104
// test iteration case 122
// test iteration case 127
// test iteration case 128
// test iteration case 133
// test iteration case 135
// test iteration case 152
// test iteration case 157
// test iteration case 160
// test iteration case 161
// test iteration case 166
// test iteration case 173
// test iteration case 178
// test iteration case 189
// test iteration case 193
// test iteration case 194
// test iteration case 200
// test iteration case 204
// test iteration case 209
// test iteration case 219
// test iteration case 225
// test iteration case 234
// test iteration case 240
// test iteration case 243
// test iteration case 254
// test iteration case 273
// test iteration case 275
// test iteration case 280
// test iteration case 1
// test iteration case 5
// test iteration case 6
// test iteration case 11
// test iteration case 21
// test iteration case 30
// test iteration case 34
// test iteration case 39
// test iteration case 41
// test iteration case 44
// test iteration case 48
// test iteration case 52
// test iteration case 60
// test case iteration 2
// test case iteration 4
// test case iteration 6
// test case iteration 10
// test case iteration 23
// test case iteration 26
// test case iteration 32
// test case iteration 35
// test case iteration 38
// test case iteration 46
// test case iteration 49
// test case iteration 50
// test case iteration 53
// test case iteration 57
// test case iteration 70
